version: '3'
services:
#  server:
#    container_name: '${APP_NAME}-server'
#    image: nginx
#    volumes:
#      - ./:/usr/share/nginx/html/
#    ports:
#      - 8181:80
#    working_dir: /usr/share/nginx/html
#    networks:
#      - app

  db:
    container_name: '${APP_NAME}-data_base'
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
    ports:
      - "3306:3306"
    networks:
      - app

  django:
    container_name: '${APP_NAME}-django'
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
        - "8000:8000"
    environment:
        - DB_ENGINE=${DB_ENGINE}
        - DB_DATABASE=${DB_DATABASE}
        - DB_USERNAME=${DB_USERNAME}
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app

  pma:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 6080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - app

  node:
    image: node
    container_name: '${APP_NAME}-node'
    working_dir: /var/www/html
#    entrypoint: 'npm'
    volumes:
      - .:/var/www/html
    networks:
      - app


networks:
    app:
        driver: bridge